
# --- Pastas ---
pasta.bd=bd/

# --- SQL Server (credenciais do grupo no servidor do ISEP) ---
db.server=ctespbd.dei.isep.ipp.pt
db.database=2026_LP2_G1_FEIRA
db.user=2026_LP2_G1_FEIRA
db.password=Grupo1_123


login.persistence.mode=sql

# --- Credenciais de arranque do admin ---

admin.email=admin@issmf.pt
admin.password.hash=Hiniqc7/OvUrr/NWdt20Uw==:mq6g/0hcbHLkY2/B8wI9IkRjKkfKWIjuF4sYJ93JALI=
